name: S-Power
markdown: redcarpet
pygments: true
permalink: /:title/
meist: <p>OÜ S-power on eesti kapitalil põhinev ettevõte, mis tegeleb alajaamade ja energiarajatiste rajamisega. Ettevõte on välja kasvanud Skanska EMV elektriosakonnast, mis asutati peale Skanska EMV elektritööde osakonna ostmist.</p><p> Ettevõttel on pikaajaline alajaamade ehitamise kogemus aastast 2003. OÜ S-Power juhtimissüteem vastab standarditele ISO 9001:2008 ja  ISO 14001:2004</p>
footer-kontakt: OÜ S-Power, Madara 25 Tallinn 10612